# -*- coding: utf-8 -*-
"""breastcancer.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/13Ql7HIqD2iYTH8N4_CaZJhgG7FYmYApW
"""

import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
from sklearn.svm import SVC
from sklearn.model_selection import GridSearchCV
from sklearn.metrics import classification_report, accuracy_score

data = pd.read_csv('/content/breast-cancer [SVM and Hyper Parm Tuning.csv')

X = data.drop(['id', 'diagnosis'], axis=1)
y = data['diagnosis'].map({'M': 1, 'B': 0})

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

scaler = StandardScaler()
X_train = scaler.fit_transform(X_train)
X_test = scaler.transform(X_test)

param_grid = {
    'C': [0.1, 1, 10, 100],
    'gamma': [1, 0.1, 0.01, 0.001],
    'kernel': ['rbf', 'linear', 'poly']
}

grid = GridSearchCV(SVC(), param_grid, refit=True, verbose=1)
grid.fit(X_train, y_train)

print(f"Best Hyperparameters: {grid.best_params_}")
grid_predictions = grid.predict(X_test)

print("\n-Model Evaluation Metrics")
print(classification_report(y_test, grid_predictions))
print(f"final Precision: {accuracy_score(y_test, grid_predictions) * 100:.2f}%")