# -*- coding: utf-8 -*-
"""titanic.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1ftMgqVivd360FqFWhUmNYAGkKc-3SARW
"""

from google.colab import files
import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.metrics import accuracy_score
from sklearn.tree import DecisionTreeClassifier

upload = files.upload()
data = pd.read_csv ('/content/Titanic Decision Tree Classifier (1).csv')

print(data.head())

features = ['Pclass','Sex','SibSp','Parch','Age','Fare']
X= data[features].copy()
y = ['Survived']
X['Age']= X['Age'].fillna(X['Age'].mean())
X['Sex']= X['Sex'].map({'male': 0 , 'female': 1})
X['Fare'] = X['Fare'].fillna(X['Fare'].mean())

y = data['Survived'] # Correctly define y as the 'Survived' column from the data DataFrame
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)
model = DecisionTreeClassifier(max_depth=3)
model.fit(X_train, y_train)
preds = model.predict(X_test)
print(f"Accuracy: {accuracy_score(y_test, preds) * 100:.2f}%")



